// C++ side of the Rust <-> C++ bridge (epic #246, ADR 0003).
//
// Wraps backend::AppBackend + backend::bridge::BackendFacade behind an opaque
// BackendBridge that cxx owns via UniquePtr. Events emitted from backend threads
// are enqueued (non-blocking) onto an internal mutex-guarded queue and drained
// by Rust via poll_events(). No Qt, no exceptions cross the boundary.
#pragma once

#include "rust/cxx.h"

#include <cstdint>
#include <memory>

namespace mib_bridge {

// Shared structs generated by cxx from src/lib.rs.
struct BridgeCameraDiscovery;
struct BridgeCameraSelection;
struct BridgeCommandResult;
struct BridgeEvent;
struct BridgeExperimentStatus;
struct BridgeFrame;
struct BridgeMonitoringSnapshot;
struct BridgeProcessingStats;
struct BridgeTriggerStatus;

class BackendBridge {
public:
    BackendBridge();
    ~BackendBridge();

    BackendBridge(const BackendBridge&) = delete;
    BackendBridge& operator=(const BackendBridge&) = delete;

    bool initialize(rust::Str data_dir);
    void shutdown();
    bool is_initialized() const;

    BridgeCommandResult configure_mock_camera(rust::Str frame_dir,
                                              std::int32_t frame_interval_ms,
                                              bool loop_files);
    BridgeCommandResult start_capture();
    BridgeCommandResult stop_capture();
    BridgeCommandResult start_frame_recording(rust::Str file_path);
    BridgeCommandResult stop_frame_recording();
    BridgeCommandResult playback_seek_latest();
    BridgeCommandResult load_recording(rust::Str file_path);
    BridgeCommandResult playback_seek_index(std::uint64_t frame_index);
    BridgeCommandResult apply_processing(bool realtime_enabled, double pixel_to_micron);
    BridgeCommandResult cancel_operation(std::uint64_t operation_id);
    BridgeCommandResult experiment_start(rust::Str output_path);
    BridgeCommandResult experiment_stop();
    BridgeCommandResult experiment_cancel();
    BridgeExperimentStatus fetch_experiment_status();
    BridgeCameraDiscovery fetch_camera_discovery();
    BridgeCameraSelection fetch_camera_selection();
    BridgeCommandResult select_hardware_camera(std::int32_t interface_index,
                                               std::int32_t device_index,
                                               rust::Str label);
    BridgeCommandResult select_mindvision_camera(std::int32_t camera_index,
                                                 rust::Str label,
                                                 rust::Str config_path);
    BridgeCommandResult apply_camera_script(rust::Str script_path);
    BridgeCommandResult reset_hardware_camera();
    BridgeCommandResult monitoring_set_active(bool active);
    BridgeCommandResult monitoring_clear();
    BridgeMonitoringSnapshot fetch_monitoring_snapshot(std::uint64_t max_rows);
    BridgeCommandResult trigger_set_pulse_duration(std::int32_t pulse_us);
    BridgeCommandResult trigger_manual_pulse();
    BridgeCommandResult trigger_periodic_start(std::int32_t interval_ms);
    BridgeCommandResult trigger_periodic_stop();
    BridgeTriggerStatus fetch_trigger_status();

    rust::Vec<BridgeEvent> poll_events();
    std::uint64_t queue_overflow_total() const;
    BridgeFrame fetch_latest_frame();
    BridgeFrame fetch_frame_by_index(std::uint64_t frame_index);
    BridgeProcessingStats fetch_processing_stats();

private:
    struct Impl;
    std::unique_ptr<Impl> impl_;
};

std::unique_ptr<BackendBridge> new_backend_bridge();
std::uint32_t bridge_abi_version();

} // namespace mib_bridge
