#!/usr/bin/env python3
"""Keep the user manual and the screenshot harness in sync.

The manual pages under docs/manual/ embed images from docs/manual/images/,
and those images are generated (not hand-captured) by the screenshot_tour
executable (src/frontend/tools/screenshot_tour_main.cpp). This check fails
when the two drift:

1. A manual page references images/<id>.png that screenshot_tour does not
   produce (the page would render a broken image forever).
2. screenshot_tour produces a shot that no manual page references (dead
   weight — either document it or remove it from the registry).

The registry is the block between SCREENSHOT_REGISTRY_BEGIN and
SCREENSHOT_REGISTRY_END markers in the harness source. Image files
themselves are NOT required to exist in the repo — they are regenerated by
the Build Windows workflow (see docs/manual/README.md).

Exit code 0 = in sync, 1 = drift detected.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
HARNESS = REPO_ROOT / "src" / "frontend" / "tools" / "screenshot_tour_main.cpp"
MANUAL_DIR = REPO_ROOT / "docs" / "manual"

REGISTRY_RE = re.compile(
    r"SCREENSHOT_REGISTRY_BEGIN(.*?)SCREENSHOT_REGISTRY_END", re.DOTALL
)
SHOT_ID_RE = re.compile(r"\{\s*\"([a-z0-9-]+)\"\s*,")
IMAGE_REF_RE = re.compile(r"!\[[^\]]*\]\(images/([A-Za-z0-9._-]+\.png)\)")


def registry_ids(errors: list[str]) -> set[str]:
    if not HARNESS.exists():
        errors.append(
            f"{HARNESS.relative_to(REPO_ROOT)}: harness source missing. The "
            f"manual's screenshots are generated by screenshot_tour; restore "
            f"the file or update scripts/check_screenshots.py."
        )
        return set()
    match = REGISTRY_RE.search(HARNESS.read_text(encoding="utf-8"))
    if not match:
        errors.append(
            f"{HARNESS.relative_to(REPO_ROOT)}: SCREENSHOT_REGISTRY_BEGIN/"
            f"END markers not found. Keep the kShots table between the "
            f"markers so this check can parse it."
        )
        return set()
    return set(SHOT_ID_RE.findall(match.group(1)))


def referenced_images() -> dict[str, list[Path]]:
    refs: dict[str, list[Path]] = {}
    for page in sorted(MANUAL_DIR.glob("*.md")):
        for match in IMAGE_REF_RE.finditer(page.read_text(encoding="utf-8")):
            refs.setdefault(match.group(1), []).append(page)
    return refs


def main() -> int:
    errors: list[str] = []
    ids = registry_ids(errors)
    refs = referenced_images()

    for image, pages in sorted(refs.items()):
        stem = image[: -len(".png")]
        if stem not in ids:
            where = ", ".join(str(p.relative_to(REPO_ROOT)) for p in pages)
            errors.append(
                f"{where}: references images/{image} but screenshot_tour has "
                f"no shot '{stem}'. Add it to the kShots registry in "
                f"{HARNESS.relative_to(REPO_ROOT)} (and capture it in the "
                f"tour), or fix the image name."
            )

    referenced_stems = {image[: -len(".png")] for image in refs}
    for stem in sorted(ids - referenced_stems):
        errors.append(
            f"{HARNESS.relative_to(REPO_ROOT)}: shot '{stem}' is generated "
            f"but no docs/manual page embeds images/{stem}.png. Reference it "
            f"in a manual page or remove it from the kShots registry."
        )

    if errors:
        print(f"check_screenshots: {len(errors)} violation(s)\n", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1
    print(f"check_screenshots: {len(ids)} shot(s) in sync with docs/manual")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
