#!/usr/bin/env python3
"""
Export metrics and images from MIB Studio HDF5 files.

This script reads HDF5 files generated by the MIB Studio application and exports
metrics (and optionally images) in the same format as the existing C++ export functions.

Usage:
    # Export CSV metrics only
    python scripts/export_hdf5.py -i experiment.h5 -o ./export --format csv

    # Export CSV + images
    python scripts/export_hdf5.py -i experiment.h5 -o ./export --format all

    # Export only valid frames
    python scripts/export_hdf5.py -i experiment.h5 -o ./export --format all --frame-type valid

Dependencies:
    - h5py: HDF5 file reading
    - numpy: Array handling
    - opencv-python (cv2): Image export (if exporting images)

Install dependencies:
    pip install h5py numpy opencv-python
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Optional, Tuple

try:
    import h5py
    import numpy as np
except ImportError as e:
    print("ERROR: Required dependencies not installed.", file=sys.stderr)
    print("Install with: pip install h5py numpy", file=sys.stderr)
    print(f"Details: {e}", file=sys.stderr)
    sys.exit(1)


# Try to import cv2 only if needed for image export
try:
    import cv2
    HAS_CV2 = True
except ImportError:
    HAS_CV2 = False


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Export metrics and images from MIB Studio HDF5 files.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument(
        "--input", "-i",
        type=str,
        required=True,
        help="Path to input .h5 file"
    )
    parser.add_argument(
        "--output", "-o",
        type=str,
        required=True,
        help="Output directory"
    )
    parser.add_argument(
        "--format", "-f",
        type=str,
        choices=["csv", "images", "all"],
        default="csv",
        help="Export format: csv (metrics only), images (images only), or all (both). Default: csv"
    )
    parser.add_argument(
        "--pixel-to-micron", "-p",
        type=float,
        default=0.4886,
        help="Pixel to micron conversion factor. Default: 0.4886"
    )
    parser.add_argument(
        "--frame-type", "-t",
        type=str,
        choices=["valid", "invalid", "both"],
        default="both",
        help="Export valid, invalid, or both frame types. Default: both"
    )
    return parser.parse_args()


def read_hdf5_metadata(h5_file: h5py.File, dataset_path: str) -> Optional[np.ndarray]:
    """
    Read metadata from HDF5 compound datatype dataset.
    
    Args:
        h5_file: Open HDF5 file handle
        dataset_path: Path to metadata dataset (e.g., "/valid_frames/metadata")
        
    Returns:
        Structured numpy array with metadata, or None if dataset doesn't exist
    """
    if dataset_path not in h5_file:
        return None
    
    dataset = h5_file[dataset_path]
    return dataset[:]  # Read entire dataset into memory


def read_hdf5_images(h5_file: h5py.File, dataset_path: str) -> Optional[np.ndarray]:
    """
    Read images from HDF5 dataset.
    
    Args:
        h5_file: Open HDF5 file handle
        dataset_path: Path to images dataset (e.g., "/valid_frames/images")
        
    Returns:
        Numpy array of images with shape (num_frames, height, width, channels), or None if dataset doesn't exist
    """
    if dataset_path not in h5_file:
        return None
    
    dataset = h5_file[dataset_path]
    return dataset[:]  # Read entire dataset into memory


def read_experiment_info(h5_file: h5py.File) -> Optional[dict]:
    """
    Read experiment info attributes from HDF5 file.
    
    Args:
        h5_file: Open HDF5 file handle
        
    Returns:
        Dictionary with experiment info, or None if group doesn't exist
    """
    if "/experiment_info" not in h5_file:
        return None
    
    info_group = h5_file["/experiment_info"]
    info = {}
    
    # Read available attributes
    for attr_name in info_group.attrs:
        info[attr_name] = info_group.attrs[attr_name]
    
    return info if info else None


def export_metrics_to_csv(
    metadata_valid: Optional[np.ndarray],
    metadata_invalid: Optional[np.ndarray],
    output_path: Path,
    pixel_to_micron: float,
    frame_type: str
) -> Tuple[int, int]:
    """
    Export metrics to CSV file matching the C++ export format.
    
    Args:
        metadata_valid: Valid frames metadata array, or None
        metadata_invalid: Invalid frames metadata array, or None
        output_path: Path to output CSV file
        pixel_to_micron: Pixel to micron conversion factor
        frame_type: "valid", "invalid", or "both"
        
    Returns:
        Tuple of (valid_count, invalid_count) frames exported
    """
    area_conversion_factor = pixel_to_micron * pixel_to_micron
    
    with open(output_path, 'w', encoding='utf-8') as f:
        # Write CSV header (matching C++ format exactly)
        f.write("Frame Type,Index,Timestamp,Deformability,Area,Area (um²),Area Ratio,Ring Ratio,")
        f.write("Valid,Touches Border,Single Inner,In Range,Inner Count,")
        f.write("Bright Q1,Bright Q2,Bright Q3,Bright Q4\n")
        
        valid_count = 0
        invalid_count = 0
        
        # Export valid frames
        if metadata_valid is not None and frame_type in ("valid", "both"):
            for row in metadata_valid:
                area_microns = row['area'] * area_conversion_factor
                f.write("Valid,")
                f.write(f"{row['index']},")
                f.write(f"{row['timestampNs']},")
                f.write(f"{row['deformability']:.3f},")
                f.write(f"{row['area']:.2f},")
                f.write(f"{area_microns:.2f},")
                f.write(f"{row['areaRatio']:.3f},")
                f.write(f"{row['ringRatio']:.3f},")
                f.write("Yes," if row['isValid'] else "No,")
                f.write("Yes," if row['touchesBorder'] else "No,")
                f.write("Yes," if row['hasSingleInnerContour'] else "No,")
                f.write("Yes," if row['inRange'] else "No,")
                f.write(f"{row['innerContourCount']},")
                f.write(f"{row['brightness_q1']:.2f},")
                f.write(f"{row['brightness_q2']:.2f},")
                f.write(f"{row['brightness_q3']:.2f},")
                f.write(f"{row['brightness_q4']:.2f}\n")
                valid_count += 1
        
        # Export invalid frames
        if metadata_invalid is not None and frame_type in ("invalid", "both"):
            for row in metadata_invalid:
                area_microns = row['area'] * area_conversion_factor
                f.write("Invalid,")
                f.write(f"{row['index']},")
                f.write(f"{row['timestampNs']},")
                f.write(f"{row['deformability']:.3f},")
                f.write(f"{row['area']:.2f},")
                f.write(f"{area_microns:.2f},")
                f.write(f"{row['areaRatio']:.3f},")
                f.write(f"{row['ringRatio']:.3f},")
                f.write("Yes," if row['isValid'] else "No,")
                f.write("Yes," if row['touchesBorder'] else "No,")
                f.write("Yes," if row['hasSingleInnerContour'] else "No,")
                f.write("Yes," if row['inRange'] else "No,")
                f.write(f"{row['innerContourCount']},")
                f.write(f"{row['brightness_q1']:.2f},")
                f.write(f"{row['brightness_q2']:.2f},")
                f.write(f"{row['brightness_q3']:.2f},")
                f.write(f"{row['brightness_q4']:.2f}\n")
                invalid_count += 1
    
    return valid_count, invalid_count


def export_images_to_tiff(
    images: np.ndarray,
    metadata: np.ndarray,
    output_dir: Path,
    frame_type_prefix: str
) -> int:
    """
    Export images to TIFF files.
    
    Args:
        images: Image array with shape (num_frames, height, width, channels)
        metadata: Metadata array with index field
        output_dir: Output directory
        frame_type_prefix: Prefix for filenames ("valid" or "invalid")
        
    Returns:
        Number of images exported
    """
    if not HAS_CV2:
        print("ERROR: opencv-python (cv2) is required for image export.", file=sys.stderr)
        print("Install with: pip install opencv-python", file=sys.stderr)
        return 0
    
    exported_count = 0
    
    for i, image in enumerate(images):
        # Get frame index from metadata
        frame_index = metadata[i]['index']
        
        # Generate filename: valid_frame_XXXXXX.tiff or invalid_frame_XXXXXX.tiff
        filename = f"{frame_type_prefix}_frame_{frame_index:06d}.tiff"
        filepath = output_dir / filename
        
        # Ensure image is in correct format (uint8, BGR for OpenCV)
        if image.dtype != np.uint8:
            # Normalize to uint8 if needed
            if image.max() > 255:
                image = (image / image.max() * 255).astype(np.uint8)
            else:
                image = image.astype(np.uint8)
        
        # Handle grayscale vs color
        if len(image.shape) == 2:
            # Grayscale
            image_bgr = image
        elif len(image.shape) == 3:
            if image.shape[2] == 1:
                # Single channel, convert to 2D
                image_bgr = image[:, :, 0]
            elif image.shape[2] == 3:
                # Already BGR/RGB (OpenCV expects BGR)
                image_bgr = image
            elif image.shape[2] == 4:
                # RGBA, convert to BGR
                image_bgr = cv2.cvtColor(image, cv2.COLOR_RGBA2BGR)
            else:
                print(f"WARNING: Unexpected image shape {image.shape} at index {i}, skipping", file=sys.stderr)
                continue
        else:
            print(f"WARNING: Unexpected image shape {image.shape} at index {i}, skipping", file=sys.stderr)
            continue
        
        # Write TIFF without compression (matching C++ behavior)
        if cv2.imwrite(str(filepath), image_bgr):
            exported_count += 1
        else:
            print(f"WARNING: Failed to write image {filepath}", file=sys.stderr)
    
    return exported_count


def main() -> int:
    """Main entry point."""
    args = parse_args()
    
    # Validate input file
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"ERROR: Input file does not exist: {input_path}", file=sys.stderr)
        return 1
    
    if not input_path.is_file():
        print(f"ERROR: Input path is not a file: {input_path}", file=sys.stderr)
        return 1
    
    # Create output directory
    output_dir = Path(args.output)
    try:
        output_dir.mkdir(parents=True, exist_ok=True)
    except OSError as e:
        print(f"ERROR: Failed to create output directory {output_dir}: {e}", file=sys.stderr)
        return 1
    
    # Check if cv2 is needed
    if args.format in ("images", "all") and not HAS_CV2:
        print("ERROR: opencv-python (cv2) is required for image export.", file=sys.stderr)
        print("Install with: pip install opencv-python", file=sys.stderr)
        return 1
    
    # Open HDF5 file
    try:
        with h5py.File(input_path, 'r') as h5_file:
            # Read metadata
            metadata_valid = None
            metadata_invalid = None
            
            if args.frame_type in ("valid", "both"):
                metadata_valid = read_hdf5_metadata(h5_file, "/valid_frames/metadata")
                if metadata_valid is None:
                    print("WARNING: /valid_frames/metadata dataset not found", file=sys.stderr)
            
            if args.frame_type in ("invalid", "both"):
                metadata_invalid = read_hdf5_metadata(h5_file, "/invalid_frames/metadata")
                if metadata_invalid is None:
                    print("WARNING: /invalid_frames/metadata dataset not found", file=sys.stderr)
            
            # Check if we have any data
            if metadata_valid is None and metadata_invalid is None:
                print("ERROR: No metadata found in HDF5 file", file=sys.stderr)
                return 1
            
            # Export CSV if requested
            if args.format in ("csv", "all"):
                csv_path = output_dir / "metrics.csv"
                valid_count, invalid_count = export_metrics_to_csv(
                    metadata_valid,
                    metadata_invalid,
                    csv_path,
                    args.pixel_to_micron,
                    args.frame_type
                )
                total_count = valid_count + invalid_count
                print(f"Exported {total_count} frames to CSV (Valid: {valid_count}, Invalid: {invalid_count})")
                print(f"CSV file: {csv_path}")
            
            # Export images if requested
            if args.format in ("images", "all"):
                total_exported = 0
                
                # Export valid frames
                if args.frame_type in ("valid", "both") and metadata_valid is not None:
                    images_valid = read_hdf5_images(h5_file, "/valid_frames/images")
                    if images_valid is not None:
                        exported = export_images_to_tiff(
                            images_valid,
                            metadata_valid,
                            output_dir,
                            "valid"
                        )
                        total_exported += exported
                        print(f"Exported {exported} valid frame images")
                    else:
                        print("WARNING: /valid_frames/images dataset not found", file=sys.stderr)
                
                # Export invalid frames
                if args.frame_type in ("invalid", "both") and metadata_invalid is not None:
                    images_invalid = read_hdf5_images(h5_file, "/invalid_frames/images")
                    if images_invalid is not None:
                        exported = export_images_to_tiff(
                            images_invalid,
                            metadata_invalid,
                            output_dir,
                            "invalid"
                        )
                        total_exported += exported
                        print(f"Exported {exported} invalid frame images")
                    else:
                        print("WARNING: /invalid_frames/images dataset not found", file=sys.stderr)
                
                print(f"Total images exported: {total_exported}")
            
            # Read and display experiment info if available
            exp_info = read_experiment_info(h5_file)
            if exp_info:
                print("\nExperiment Info:")
                for key, value in sorted(exp_info.items()):
                    print(f"  {key}: {value}")
    
    except IOError as e:
        print(f"ERROR: Failed to open HDF5 file: {e}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"ERROR: Unexpected error: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        return 1
    
    print(f"\nExport complete. Output directory: {output_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
