function(mib_link_opencv target visibility)
    if(TARGET opencv_world)
        target_link_libraries(${target} ${visibility} opencv_world)
    elseif(TARGET opencv_core)
        target_link_libraries(${target} ${visibility} opencv_core opencv_imgproc opencv_imgcodecs opencv_videoio)
    elseif(DEFINED OpenCV_LIBS)
        target_include_directories(${target} ${visibility} ${OpenCV_INCLUDE_DIRS})
        target_link_libraries(${target} ${visibility} ${OpenCV_LIBS})
    endif()
endfunction()

function(mib_link_sqlite target visibility)
    if(SQLite3_FOUND)
        target_link_libraries(${target} ${visibility} SQLite::SQLite3)
    elseif(TARGET unofficial::sqlite3::sqlite3)
        target_link_libraries(${target} ${visibility} unofficial::sqlite3::sqlite3)
    elseif(TARGET sqlite3)
        target_link_libraries(${target} ${visibility} sqlite3)
    endif()
endfunction()

function(mib_link_hdf5 target visibility)
    # HDF5 linking - using C API (hdf5.lib and hdf5_hl.lib).
    # Try imported targets first, then fallback to manual linking.
    if(TARGET hdf5::hdf5-shared)
        target_link_libraries(${target} ${visibility} hdf5::hdf5-shared)
    elseif(TARGET hdf5::hdf5)
        target_link_libraries(${target} ${visibility} hdf5::hdf5)
    elseif(TARGET hdf5::hdf5_cpp-shared)
        target_link_libraries(${target} ${visibility} hdf5::hdf5_cpp-shared)
    elseif(TARGET hdf5::hdf5-cpp)
        target_link_libraries(${target} ${visibility} hdf5::hdf5-cpp)
    elseif(TARGET HDF5::HDF5)
        target_link_libraries(${target} ${visibility} HDF5::HDF5)
    else()
        # Fallback: manually link HDF5 libraries from Conan.
        set(CONAN_LIB_PATHS
            "${CMAKE_BINARY_DIR}/conan"
            "${CMAKE_PREFIX_PATH}"
        )
        find_library(HDF5_LIB hdf5 PATHS ${CONAN_LIB_PATHS} PATH_SUFFIXES lib NO_DEFAULT_PATH)
        find_library(HDF5_HL_LIB hdf5_hl PATHS ${CONAN_LIB_PATHS} PATH_SUFFIXES lib NO_DEFAULT_PATH)
        if(HDF5_LIB AND HDF5_HL_LIB)
            target_link_libraries(${target} ${visibility} ${HDF5_LIB} ${HDF5_HL_LIB})
            message(STATUS "Linked HDF5 libraries manually: ${HDF5_LIB} ${HDF5_HL_LIB}")
        elseif(HDF5_FOUND)
            # Use variables from find_package if available.
            if(HDF5_INCLUDE_DIRS)
                target_include_directories(${target} ${visibility} ${HDF5_INCLUDE_DIRS})
            endif()
            if(HDF5_LIBRARIES)
                target_link_libraries(${target} ${visibility} ${HDF5_LIBRARIES})
            endif()
        else()
            message(WARNING "HDF5 libraries not found - HDF5 functionality will not be available")
        endif()
    endif()
endfunction()
